# Generated by Django 3.2.9 on 2021-12-21 22:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('AntartidaFront', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tipomedicion',
            managers=[
                ('tipo_mediciones_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='unidad_de_medida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
